[2025-10-20T23:36:55.558+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T23:36:55.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1_TaskFlow_FileIO.merge_scaled_task manual__2025-10-20T23:35:58.452593+00:00 [queued]>
[2025-10-20T23:36:55.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1_TaskFlow_FileIO.merge_scaled_task manual__2025-10-20T23:35:58.452593+00:00 [queued]>
[2025-10-20T23:36:55.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T23:36:55.613+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_scaled_task> on 2025-10-20 23:35:58.452593+00:00
[2025-10-20T23:36:55.624+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=345) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-20T23:36:55.627+0000] {standard_task_runner.py:63} INFO - Started process 358 to run task
[2025-10-20T23:36:55.626+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1_TaskFlow_FileIO', 'merge_scaled_task', 'manual__2025-10-20T23:35:58.452593+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpdute4s_k']
[2025-10-20T23:36:55.631+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask merge_scaled_task
[2025-10-20T23:36:55.700+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1_TaskFlow_FileIO.merge_scaled_task manual__2025-10-20T23:35:58.452593+00:00 [running]> on host 0074cd054b76
[2025-10-20T23:36:55.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1_TaskFlow_FileIO' AIRFLOW_CTX_TASK_ID='merge_scaled_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T23:35:58.452593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T23:35:58.452593+00:00'
[2025-10-20T23:36:55.831+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T23:36:55.834+0000] {airflow.py:75} INFO - Merging / preparing scaled data at /opt/***/dags/data/scaled.npy
[2025-10-20T23:36:55.835+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/dags/data/scaled.npy
[2025-10-20T23:36:55.836+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T23:36:55.867+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab1_TaskFlow_FileIO, task_id=merge_scaled_task, run_id=manual__2025-10-20T23:35:58.452593+00:00, execution_date=20251020T233558, start_date=20251020T233655, end_date=20251020T233655
[2025-10-20T23:36:55.925+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-20T23:36:55.956+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-10-20T23:36:55.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
